apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: scheduled-pod-kill
  namespace: default
spec:
  schedule: "*/1 * * * *"  
  type: PodChaos
  historyLimit: 5  
  concurrencyPolicy: Forbid  
  podChaos:
    action: pod-kill
    mode: one  
    selector:
      namespaces:
        - default
    duration: "30s"