apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  # name of the Test Workflow
  name: k6smoketest 
  namespace: testkube 
  labels: 
    tool: k6
    type: smoke 
spec: 
  content: 
    # Git repository from which the test will be imported
    git: 
      uri: https://github.com/FraNemo/testkube/ 
      revision: main
      paths:
        - tests/T6-SimTest.js
  # steps that will be executed by this Test Workflow
  steps: 
  - name: Run Smoke Test
    workingDir: /data/repo/tests
    run:
      image:  grafana/k6:0.49.0
      env: 
      - name: K6_WEB_DASHBOARD
        value: "true"
      - name: K6_WEB_DASHBOARD_EXPORT
        value: /data/k6-sim-report.html
      args: # args passed to the container
      - run 
      - --out
      - influxdb=http://influxdb.default.svc.cluster.local:8086/k6db
      - T6-SimTest.js
    artifacts: 
      workingDir: /data
      paths: 
      - k6-sim-report.html
