apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  # name of the Test Workflow
  name: k6simtest 
  namespace: testkube 
  labels: 
    tool: k6
    type: simulation 
spec: 
  config: 
    #parameters that can be passed to the test
    testname: 
      type: string
      default: tests/T6-SimTest.js
    reportname:
      type: string
      default: k6-sim-report.html
  content: 
    # Git repository from which the test will be imported
    git: 
      uri: https://github.com/FraNemo/testkube/ 
      revision: main
      paths:
        - tests/{{ config.testname }}
  # steps that will be executed by this Test Workflow
  steps: 
  - name: Run Smoke Test
    workingDir: /data/repo/tests
    run:
      image:  grafana/k6:0.49.0
      env: 
      - name: K6_WEB_DASHBOARD
        value: "true"
      - name: K6_WEB_DASHBOARD_EXPORT
        value: /data/{{ config.reportname }}
      args: # args passed to the container
      - run 
      - '{{ config.testname }}'
    artifacts: 
      workingDir: /data
      paths: 
      - '{{ config.reportname }}'
